In LeetCode Store, there are some kinds of items to sell. Each item has a price.

However, there are some special offers, and a special offer consists of one or more different kinds of items with a sale price.

You are given the each item's price, a set of special offers, and the number we need to buy for each item. The job is to output the lowest price you have to pay for exactly certain items as given, where you could make optimal use of the special offers.

Each special offer is represented in the form of an array, the last number represents the price you need to pay for this special offer, other numbers represents how many specific items you could get if you buy this offer.

You could use any of special offers as many times as you want.

Example 1:
Input: [2,5], [[3,0,5],[1,2,10]], [3,2]
Output: 14
Explanation: 
There are two kinds of items, A and B. Their prices are $2 and $5 respectively. 
In special offer 1, you can pay $5 for 3A and 0B
In special offer 2, you can pay $10 for 1A and 2B. 
You need to buy 3A and 2B, so you may pay $10 for 1A and 2B (special offer #2), and $4 for 2A.
Example 2:
Input: [2,3,4], [[1,1,0,4],[2,2,1,9]], [1,2,1]
Output: 11
Explanation: 
The price of A is $2, and $3 for B, $4 for C. 
You may pay $4 for 1A and 1B, and $9 for 2A ,2B and 1C. 
You need to buy 1A ,2B and 1C, so you may pay $4 for 1A and 1B (special offer #1), and $3 for 1B, $4 for 1C. 
You cannot add more items, though only $9 for 2A ,2B and 1C.
Note:
There are at most 6 kinds of items, 100 special offers.
For each item, you need to buy at most 6 of them.
You are not allowed to buy more items than you want, even if that would lower the overall price.

In [ ]:
import numpy
class Solution(object):
    def shoppingOffers(self, price, special, needs):
        """
        :type price: List[int]
        :type special: List[List[int]]
        :type needs: List[int]
        :rtype: int
        """
        price=numpy.array(price)
        special=numpy.array(special)
        needs=numpy.array(needs)
        self.res=price.dot(needs)
        #regBuy=numpy.column_stack((numpy.identity(len(price)),price))
        #units=numpy.vstack((special,regBuy))
        self.dfs(0,special,needs,numpy.zeros(len(needs),dtype=numpy.int))
        return int(self.res)
                                  
    def dfs(self,currVal,special,needs,purchased):
        
        if currVal>=self.res:
            return
        if any(purchased>needs):
            return
        if sum(needs==purchased)==len(needs):
            self.res=currVal
            return                      
        for u in special:
            self.dfs(currVal+u[-1],special,needs,purchased+u[:-1])
        

In [12]:
import numpy
class Solution(object):
    def shoppingOffers(self, price, special, needs):
        """
        :type price: List[int]
        :type special: List[List[int]]
        :type needs: List[int]
        :rtype: int
        """
        price=numpy.array(price)
        special=numpy.array(special)
        needs=numpy.array(needs)
        self.res=price.dot(needs)
        regBuy=numpy.column_stack((numpy.identity(len(price)),price))
        units=numpy.vstack((special,regBuy))
        self.dfs(0,units,needs,numpy.zeros(len(needs),dtype=numpy.int))
        return int(self.res)
                                  
    def dfs(self,currVal,units,needs,purchased):
        
        if currVal>=self.res:
            return
        if any(purchased>needs):
            return
        if sum(needs==purchased)==len(needs):
            self.res=currVal
            return                      
        for u in units:
            self.dfs(currVal+u[-1],units,needs,purchased+u[:-1])
        

In [48]:
price=numpy.array([1,2,3])
special=numpy.array([[2,1,0,3]])
p=numpy.column_stack((numpy.identity(len(price)),price))


In [51]:
units=numpy.vstack((special,p))


In [14]:
s=Solution()
s.shoppingOffers([4,3,2,9,8,8],
[[1,5,5,1,4,0,18],[3,3,6,6,4,2,32]],
[6,5,5,6,4,1])

KeyboardInterrupt: 

In [6]:
b==c

True

In [5]:
import numpy as np

In [19]:
np.identity(2)

array([[ 1.,  0.],
       [ 0.,  1.]])

In [6]:
a=np.array([2,3])
b=np.array([2,2])

In [17]:
a.dot()

10

In [27]:
e=np.identity(2)

In [29]:
e[:,1]

array([ 0.,  1.])

In [35]:
f=np.vstack((b,a))

In [39]:
for t in f:
    print(t[1])

2
3


In [42]:
b2=np.array([10,20,30])

In [43]:
b+b2[:-1]

array([12, 22])

In [8]:
any(a>b)

True

In [58]:
len(a)

2